# hlpedit_ui.pm --
#
# UI generated by GUI Builder Build 146 on 2012-09-19 13:04:39 from:
#    D:/hobby/Z9001-Mega-Flash/dev/hlpedit/hlpedit.ui
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Declare the package for this dialog
package hlpedit;

use Tk;
use Tk::Menu;

# hlpedit::ui --
#
# ARGS:
#   root     the parent window for this form
#
sub hlpedit::ui {
    our($root) = @_;


    # Widget Initialization
    our($_frame_2) = $root->Frame(
    );
    our($text) = $root->Text(
	-background => "#000000",
	-font => '{Courier New} 12',
	-foreground => "#00ff00",
	-insertbackground => "#ffff00",
	-width => 40,
    );
    our($scrollbary) = $root->Scrollbar(
    );
    our($btn_red) = $root->Button(
	-activebackground => "#ff0000",
	-background => "#ff0000",
	-text => " ",
    );
    our($btn_green) = $root->Button(
	-activebackground => "#00ff00",
	-background => "#00ff00",
	-text => " ",
    );
    our($_button_3) = $root->Button(
	-activebackground => "#ffff00",
	-background => "#ffff00",
	-text => " ",
    );
    our($_button_4) = $root->Button(
	-activebackground => "#0000ff",
	-background => "#0000ff",
	-text => " ",
    );
    our($_button_5) = $root->Button(
	-activebackground => "#ff00ff",
	-background => "#ff00ff",
	-text => " ",
    );
    our($_button_6) = $root->Button(
	-activebackground => "#00ffff",
	-background => "#00ffff",
	-text => " ",
    );
    our($_button_7) = $root->Button(
	-activebackground => "#ffffff",
	-background => "#ffffff",
	-text => " ",
    );
    our($_button_8) = $root->Button(
	-text => "X",
    );
    our($menu) = $root->Menu(
    );

    # widget commands

    $text->configure(
	-xscrollcommand => \&text_xscrollcommand
    );
    $text->configure(
	-yscrollcommand => [set => $scrollbary]
    );
    $scrollbary->configure(
	-command => [yview => $text]
    );
    $btn_red->configure(
	-command => [\&btn_color, 'RED']
    );
    $btn_green->configure(
	-command => [\&btn_color, 'GREEN']
    );
    $_button_3->configure(
	-command => [\&btn_color, 'YELLOW']
    );
    $_button_4->configure(
	-command => [\&btn_color, 'BLUE']
    );
    $_button_5->configure(
	-command => [\&btn_color, 'MAGENTA']
    );
    $_button_6->configure(
	-command => [\&btn_color, 'CYAN']
    );
    $_button_7->configure(
	-command => [\&btn_color, 'WHITE']
    );
    $_button_8->configure(
	-command => [\&btn_color]
    );
    our($menuitem1) = $root->Menu(
	-tearoff => 0,
    );
    $menu->cascade(
	-label => "File",
	-menu => $menuitem1,
    );
    our($menuitem2) = $root->Menu(
	-tearoff => 0,
    );
    $menu->cascade(
	-label => "Hilfe",
	-menu => $menuitem2,
    );
    $menuitem1->command(
	-accelerator => "F2",
	-command => \&mb_load,
	-label => "Laden",
    );
    $menuitem1->command(
	-accelerator => "F3",
	-command => \&mb_save,
	-label => "Speichern",
    );
    $menuitem2->command(
	-command => \&mb_help,
	-label => "\x{DC}ber...",
    );
    $menuitem1->command(
	-accelerator => "F4",
	-command => \&mb_saveas,
	-label => "Speichern als...",
    );


    # Geometry Management
    $_frame_2->grid(
	-in     => $root,
	-column => 1,
	-row    => 1,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "news"
    );
    $text->grid(
	-in     => $root,
	-column => 1,
	-row    => 2,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "news"
    );
    $scrollbary->grid(
	-in     => $root,
	-column => 2,
	-row    => 2,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "ns"
    );
    $btn_red->grid(
	-in     => $_frame_2,
	-column => 1,
	-row    => 1,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "nsew"
    );
    $btn_green->grid(
	-in     => $_frame_2,
	-column => 2,
	-row    => 1,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "nsew"
    );
    $_button_3->grid(
	-in     => $_frame_2,
	-column => 3,
	-row    => 1,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "nsew"
    );
    $_button_4->grid(
	-in     => $_frame_2,
	-column => 4,
	-row    => 1,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "nsew"
    );
    $_button_5->grid(
	-in     => $_frame_2,
	-column => 5,
	-row    => 1,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "nsew"
    );
    $_button_6->grid(
	-in     => $_frame_2,
	-column => 6,
	-row    => 1,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "nsew"
    );
    $_button_7->grid(
	-in     => $_frame_2,
	-column => 7,
	-row    => 1,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "nsew"
    );
    $_button_8->grid(
	-in     => $_frame_2,
	-column => 8,
	-row    => 1,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "nsew"
    );


    # Resize Behavior
    $root->gridRowconfigure(1, -weight => 0, -minsize => 22, -pad => 0);
    $root->gridRowconfigure(2, -weight => 1, -minsize => 237, -pad => 0);
    $root->gridColumnconfigure(1, -weight => 1, -minsize => 292, -pad => 0);
    $root->gridColumnconfigure(2, -weight => 0, -minsize => 2, -pad => 0);
    $_frame_2->gridRowconfigure(1, -weight => 0, -minsize => 40, -pad => 0);
    $_frame_2->gridColumnconfigure(1, -weight => 0, -minsize => 40, -pad => 0);
    $_frame_2->gridColumnconfigure(2, -weight => 0, -minsize => 40, -pad => 0);
    $_frame_2->gridColumnconfigure(3, -weight => 0, -minsize => 40, -pad => 0);
    $_frame_2->gridColumnconfigure(4, -weight => 0, -minsize => 40, -pad => 0);
    $_frame_2->gridColumnconfigure(5, -weight => 0, -minsize => 40, -pad => 0);
    $_frame_2->gridColumnconfigure(6, -weight => 0, -minsize => 40, -pad => 0);
    $_frame_2->gridColumnconfigure(7, -weight => 0, -minsize => 40, -pad => 0);
    $_frame_2->gridColumnconfigure(8, -weight => 0, -minsize => 40, -pad => 0);
    $_frame_2->gridColumnconfigure(9, -weight => 1, -minsize => 40, -pad => 0);
    $root->configure(-menu => $menu)
}

1;
